//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFlowSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryID { get; set; }
        public int IngredientID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime LastDeliveryDate { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
    }
}
