//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestFlowSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetails
    {
        public int PurchaseDetailID { get; set; }
        public int PurchaseID { get; set; }
        public int IngredientID { get; set; }
        public decimal Quantity { get; set; }
        public decimal UnitPrice { get; set; }
        public decimal ItemTotal { get; set; }
    
        public virtual Ingredients Ingredients { get; set; }
        public virtual Purchases Purchases { get; set; }
    }
}
